### ISSUE TITLE
icon not updated when value changes to 0

### ISSUE THREAD

**Issue by rserbitar** [jessev14/resource-icons#7]
The icon is not updated when the value of the shown reasource changes from 1 to 0 or from -1 to 0 (maybe also from any value to 0, I have not tested that).
If the values is changed from 0 to 1 or from 0 to -1 it is again updated.

**Comment by rserbitar** [comment]
I think the problem is here:

    // Create new method in Token class to update resouce icon values
    CONFIG.Token.objectClass.prototype.updateResourceIconValues = updateResourceIconValues;
    function updateResourceIconValues() {
        if (!this.data.flags["resource-icons"]) return;
        for (let icon of ["icon1", "icon2", "icon3"]) {
            // Get value of resource for current icon
            const resourceValue = foundry.utils.getProperty(this.actor.data.data, this.data.flags["resource-icons"][icon].resource);
            if (!resourceValue) continue;  <---- should check for NULL or UNDEFINED not also 0?
            let value;
            if (Number.isFinite(resourceValue)) value = resourceValue; <---- does this check for 0? or just other cases?
            else if ("value" in resourceValue) value = resourceValue.value || 0;
            else value = null;
            // Update current icon text to reflect new value
            this.resourceIcons[icon].value.text = value;
        }
    }

**Comment by jessev14** [comment]
I'm not able to reproduce this error. https://streamable.com/73mjhj
It may be the case that there's something about the resource you're trying to track that I haven't accounted for in the code.

**Comment by rserbitar** [comment]
The game system where I experience the problem is hexxen. Will upload a video later, thanks for checking.

**Comment by rserbitar** [comment]
I attach 4 pictures where one cans ee the behaviour at 2,1,0 and -1 resource
![-1](https://user-images.githubusercontent.com/8320468/170529440-de60d611-6e18-4e19-917f-ab8edd1bb126.png)
![0](https://user-images.githubusercontent.com/8320468/170529462-23c5cf0f-185b-4fd8-bb30-8f34c15b3d1c.png)
![1](https://user-images.githubusercontent.com/8320468/170529474-8787c774-88bb-478b-8ebe-8431257c866d.png)
![2](https://user-images.githubusercontent.com/8320468/170529485-ffaacf0d-6327-4ca8-b8d0-78ae834a019a.png)
.

**Comment by dodgepong** [comment]
I can reproduce this as well. This happens when the referenced attribute is an integer -- "0" values are not getting their value text passed through because they are treated as false-y.

@jessev14 The reason you're not able to reproduce is because many of the values in the DnD5e system are actually objects containing a value, not integers directly. If you want to repro with DnD5e, try setting the resource to track an integer value, such as `abilities.dex.value`.

I believe @rserbitar's analysis is correct: the `if (!resourceValue) continue;` gate is preventing integer values of 0 from getting updated. This should be `if (resourceValue == null) continue;` as it was in a previous iteration of the file if the intent is to ensure that the resource is set to something useful.

**Comment by jessev14** [comment]
@dodgepong yep, you got it. much appreciated. I'm releasing a version with this fix (and a hotfix for the hideZero thing).
